# Generated by Django 5.2.3 on 2025-06-29 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'A-'), ('5', 'B-'), ('6', 'C-'), ('7', 'O-'), ('8', 'AB+'), ('9', 'AB-')], max_length=3)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=400, null=True)),
                ('salary', models.IntegerField(default=0)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.department')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.role')),
            ],
        ),
    ]
