# Generated by Django 5.2.3 on 2025-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('blood_group', models.CharField(choices=[('1', 'A+'), ('2', 'B+'), ('3', 'O+'), ('4', 'A-'), ('5', 'B-'), ('6', 'C-'), ('7', 'O-'), ('8', 'AB+'), ('9', 'AB-')], max_length=3)),
                ('Department', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('phone', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('hire_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
