# Generated by Django 5.2.3 on 2025-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_department_alter_employee_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='Position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Department',
            new_name='dept',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
